version: '3.9'

services:
  readyapi_mysql:
    image: mysql:latest
    container_name: readyapi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - 1-volume:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  1-volume:

#    ssl-ca=/var/lib/mysql/ca-cert.pem
#    ssl-cert=/var/lib/mysql/client-cert.pem
#    ssl-key=/var/lib/mysql/client-key.pem