      version: '3.9'

      services:
        readyapi_mysql:
          image: mysql:latest
          container_name: readyapi_mysql
          environment:
            MYSQL_ROOT_PASSWORD: password
          volumes:
            - mysql_data:/var/lib/mysql
          command:
            - --bind-address=0.0.0.0
          ports:
            - 3306:3306

      volumes:
        mysql_data:
