version: '3.9'

services:
  readyapi_mysql:
    image: mysql:latest
    container_name: readyapi_mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - /Users/konrad.krasocki/Library/Application Support/MySQL/Workbench/certificates/62227408-322F-48AB-92C2-862A4F5F7D17:/etc/mysql/certs
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command:
      - --ssl-ca=/etc/mysql/certs/ca-cert.pem
      - --ssl-cert=/etc/mysql/certs/server-cert.pem
      - --ssl-key=/etc/mysql/certs/server-key.pem
      - --ssl=1
      - --bind-address=0.0.0.0
    ports:
      - 3306:3306

volumes:
  mysql_data:


