version: '3.9'

services:
  readyapi_mysql:
    image: mysql:latest
    container_name: readyapi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306


# Copy this to your my.cnf file. Please change <directory> to the corresponding
# directory where the files were copied.
#  [client]
#  ssl-ca=<directory>/ca-cert.pem
#  ssl-cert=<directory>/client-cert.pem
#  ssl-key=<directory>/client-key.pem
#
#  [mysqld]
#  ssl-ca=<directory>/ca-cert.pem
#  ssl-cert=<directory>/server-cert.pem
#  ssl-key=<directory>/server-key.pem